name: Get East Asian TV Shows

on:
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Allow GitHub Actions to commit changes

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        pip install requests

    - name: Run TV show scraper
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        python get-eastasian-tvshows.py

    - name: Commit scraped data
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add east_asian_tvshows.csv
        git commit -m "Update East Asian TV shows" || echo "No changes to commit"
        git push

